server:
  port: 12333


api:

  #  天气查询的城市ID
  district_id: ''
  #  应用AK
  ak: ''
  #  纪念日：注意格式 yyyy-MM-dd
  loveDate: '2021-08-23'
  #  生日：注意格式 yyyy-MM-dd
  birthday: '1998-08-23'
  #  天行数据apiKey
  rainbowKey: ''

  qweatherKey: ''
  #位置信息
  qweatherLocation: ''
  qweatherType: ''

spring:
  mail:
    host: smtp.qq.com
    username: wfgmqhx@qq.com
    #发送人
    nickname: 大秦
    #授权码
    password: 
    port: 465
    protocol: smtps
    default-encoding: utf-8


